import { Usermanagement } from '@/servers/usermanagement'

export const items = (queryInfo: Usermanagement) => [
  {
    label: '账号名称',
    key: 'uapAccountNickName',
    widget: 'input',
    initialValue: queryInfo?.uapAccountNickName,
    required: true,
    widgetProps: {},
    placeholder: '请输入账号名称',
  },
  {
    label: '用户真实姓名',
    key: 'uapUserRealName',
    widget: 'input',
    initialValue: queryInfo?.uapUserRealName,
    required: true,
    placeholder: '请输入用户真实姓名',
  },
  // {
  //   label: '性别',
  //   key: 'uapUserGender',
  //   widget: 'radio',
  //   initialValue: queryInfo?.uapUserGender,
  //   required: true,
  //   option: [
  //     { label: '男', value: '10' },
  //     { label: '女', value: '20' },
  //   ],
  // },
  {
    label: '角色名称',
    key: 'uapRoleName',
    widget: 'input',
    initialValue: queryInfo?.uapRoleName,
    required: true,
    placeholder: '请输入角色名称',
  },
  // {
  //   label: '民族',
  //   key: 'uapUserNation',
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserNation,
  //   required: true,
  //   placeholder: '请输入民族',
  // },
  // {
  //   label: '政治面貌',
  //   key: 'uapUserPolitical',
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserPolitical,
  //   required: true,
  //   placeholder: '请输入政治面貌',
  // },
  // {
  //   label: '籍贯',
  //   key: 'uapUserNationPlace',
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserNationPlace,
  //   required: true,
  //   placeholder: '请输入籍贯',
  // },
  // {
  //   label: '身份证号',
  //   key: 'uapUserIdCard',
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserIdCard,
  //   required: true,
  //   placeholder: '请输入身份证号',
  // },
  // {
  //   label: '联系座机',
  //   key: 'uapUserTel',
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserTel,
  //   required: true,
  //   placeholder: '请输入联系座机',
  // },
  // {
  //   label: '手机',
  //   key: 'uapUserMobile',
  //   widgetProps: {},
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserMobile,
  //   required: true,
  //   placeholder: '请输入手机',
  // },
  // {
  //   label: '邮箱',
  //   key: 'uapUserEmail',
  //   widget: 'input',
  //   initialValue: queryInfo?.uapUserEmail,
  //   required: true,
  //   placeholder: '请输入邮箱',
  // },
  // {
  //   label: '户口地址',
  //   key: 'uapUserNativeAddress',
  //   widget: 'textarea',
  //   initialValue: queryInfo?.uapUserNativeAddress,
  //   required: true,
  //   placeholder: '请输入户口地址',
  // },
  // {
  //   label: '现居住地址',
  //   key: 'uapUserAddress',
  //   widget: 'textarea',
  //   initialValue: queryInfo?.uapUserAddress,
  //   required: true,
  //   placeholder: '请输入现居住地址',
  // },
]
