default:
  image: node:14

services:
  - name: docker:19.03.13-dind
    command:
      [
        "--registry-mirror=https://docker.mirrors.ustc.edu.cn",
        "--insecure-registry=192.168.188.222:5008"
      ]

stages:
  - build
  - deploy

Build Static:
  stage: build
  only:
    - master
    - dev
  before_script:
    - pwd
    - ls -al
    - npm install
  artifacts:
    paths:
      - build
  script:
    - npm run build


Docker Imgae Build Dev:
  stage: deploy
  image: docker:19
  only:
    - master
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - pwd
    - ls -al
    - docker build --pull -t "$CI_REGISTRY"/"$CI_PROJECT_PATH":latest .
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH":latest
    - echo "$CI_REGISTRY"/"$CI_PROJECT_PATH"

Docker Imgae Build:
  stage: deploy
  image: docker:19
  only:
    - tags
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "$CI_COMMIT_TAG"
    - VERSION=$(echo $CI_COMMIT_TAG | sed -e 's/^v//')
    - echo $VERSION
    - export V=$VERSION
    - echo "$V"
    - docker build --pull -t "$CI_REGISTRY"/"$CI_PROJECT_PATH":"$V" .
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH":"$V"
    - ls -al

