import { Change } from '@/servers/BasicManage/ChargeManage'

export const items = (queryInfo: Change, tableType: string) => [
  {
    label: '商业区',
    key: 'types',
    widget: 'select',
    option: [
      { label: '中心区商业街', value: '中心区商业街' },
      { label: '瀚海大道商业街', value: '瀚海大道商业街' },
      { label: '经济开发区', value: '经济开发区' },
      { label: 'xxx', value: 'xxx' },
    ],
    initialValue: queryInfo?.types,
    widgetProps: {},
    required: true,
    placeholder: '请选择商业区',
    rules: [{ required: true, message: '请选择商业区' }],
  },
  {
    label: '编号',
    key: 'number',
    widget: 'input',
    initialValue: queryInfo?.chargeName,
    required: true,
    rules: [{ required: true, message: '请输入编号' }],
  },
  {
    label: '楼层',
    key: 'floor',
    widget: 'input',
    initialValue: queryInfo?.chargeName,
    required: true,
    hide: tableType === 'view' ? true : false,
    rules: [{ required: true, message: '请输入楼层' }],
  },
  {
    label: '占地面积',
    key: 'area',
    widget: 'input',
    initialValue: queryInfo?.chargeName,
    required: true,
    hide: tableType === 'view' ? true : false,
    rules: [{ required: true, message: '请输入占地面积' }],
  },
  {
    label: '使用面积',
    key: 'use',
    widget: 'input',
    initialValue: queryInfo?.chargeName,
    required: true,
    hide: tableType === 'view' ? true : false,
    rules: [{ required: true, message: '请输入使用面积' }],
  },
  {
    label: '租金',
    key: 'rent',
    widget: 'input',
    initialValue: queryInfo?.chargeName,
    hide: tableType === 'view' ? true : false,
    rules: [{ required: true, message: '请输入使用面积' }],
  },
  {
    label: '使用状态',
    key: 'status',
    widget: 'select',
    disabled: true,
    option: [
      { label: '空置', value: '空置' },
      { label: '已出租', value: '已出租' },
      { label: '已出售', value: '已出售', },
    ],
    initialValue: queryInfo?.types,
    widgetProps: {},
    required: true,
    placeholder: '请选择使用状态',
    rules: [{ required: true, message: '请选择使用状态' }],
  },
  {
    label: '备注',
    key: 'univalent',
    widget: 'textarea',
    initialValue: queryInfo?.univalent,
    hide: tableType === 'view' ? true : false,
  },
]
