import { Change } from '@/servers/BasicManage/ChargeManage'

export const items = (queryInfo: Change, tableType: string) => [
  {
    label: '类型',
    key: 'chargeType',
    widget: 'select',
    option: [
      { label: '常规收费项', value: '常规收费项' },
      { label: '临时收费项', value: '临时收费项' },
      { label: '押金类收费项', value: '押金类收费项' },
    ],
    initialValue: queryInfo?.chargeType,
    widgetProps: {},
    required: true,
    placeholder: '请选择类型',
    rules: [{ required: true, message: '请选择类型' }],
  },
  {
    label: '收费项目名',
    key: 'chargeName',
    widget: 'input',
    initialValue: queryInfo?.chargeName,
    required: true,
    rules: [{ required: true, message: '请输入收费项目名' }],
  },
  {
    label: '单价',
    key: 'chargePrice',
    widget: 'input',
    initialValue: queryInfo?.chargePrice,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入单价' }],
  },
  {
    label: '数量',
    key: 'chargeNumType',
    widget: 'input',
    initialValue: queryInfo?.chargeNumType,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入数量' }],
  },
  {
    label: '计算公式',
    key: 'chargeFormula',
    widget: 'input',
    initialValue: queryInfo?.chargeFormula,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入计算公式' }],
  },
  {
    label: '计算周期',
    key: 'chargeMonth',
    widget: 'input',
    initialValue: queryInfo?.chargeMonth,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入计算周期' }],
  },
  {
    label: '滞纳金',
    key: 'chargeLateType',
    widget: 'input',
    initialValue: queryInfo?.chargeLateType,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入滞纳金' }],
  },
  {
    label: '滞纳金比例',
    key: 'chargeLateProportion',
    widget: 'input',
    initialValue: queryInfo?.chargeLateProportion,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入滞纳金比例' }],
  },
  {
    label: '滞纳金天数',
    key: 'chargeDay',
    widget: 'input',
    initialValue: queryInfo?.chargeDay,
    required: true,
    hide: tableType === 'edit' ? false : true,
    rules: [{ required: true, message: '请输入滞纳金天数' }],
  },
]
