module.exports.authList = [
  '/home',
  '/register',
  '/UserManagement',
  '/UserManagement/User',
  '/chargeManagement',
  '/chargeManagement/propertyCharge',
  '/chargeManagement/propertyCharge/shopCharge',
  '/chargeManagement/propertyCharge/temporaryCharges',
  '/Authority',
  '/Authority/Application',

  '/dom',
  '/dom/courses',
  '/dom/home',
  '/demo',
  '/exceptions',
  '/exceptions/403',
  '/exceptions/404',
  '/exceptions/500',
]
